---
packages:
  copr:
  install:
    - alsa-utils
    - audit
    - default-fonts
    - distrobox
    - ffmpeg
    - ffmpeg-libs
    - firefox
    - firewalld
    - flatpak
    - flatpak-spawn
    - fzf
    - git
    - google-noto-color-emoji-fonts
    - google-noto-emoji-fonts
    - google-noto-sans-balinese-fonts
    - google-noto-sans-cjk-fonts
    - google-noto-sans-javanese-fonts
    - google-noto-sans-sundanese-fonts
    - htop
    - just
    - nvtop
    - openrgb-udev-rules
    - pipewire-codec-aptx
    - procs
    - rsync
    - tcpdump
    - tmux
    - traceroute
    - tree
    - wireguard-tools
    - zip
    - zstd

    # Network
    - systemd-networkd
    - systemd-networkd-defaults

  uninstall:
    - ffmpeg-free
systemd:
  enable:
    - firewalld.service
  #   - podman.socket
  #   - systemd-networkd
  disable:
  #   - NetworkManager
