name: Build bootc image
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "justfile"
      - "brew.yml"
      - ".github/**"
    branches:
      - main
  schedule:
    - cron: "5 4 * * 2,5" # Should be after official fedora pushes

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      IMAGE_TAG: latest
      IMAGE_NAME: ${{ github.event.repository.name }}
      REGISTRY: ghcr.io/${{ github.repository_owner }}

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-large-packages: "true"
          remove-cached-tools: "true"
          remove-swapfile: "true"
          verbose: "false"
      # Based on https://github.com/orgs/community/discussions/25678
      # Uncomment if builder runs out of space
      # - name: Delete huge unnecessary tools folder
      #   run: |
      #     rm -rf /opt/hostedtoolcache
      #     rm -rf /usr/share/dotnet

      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build image
        id: build-image
        shell: bash
        run: sudo podman build -t localhost/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Rechunk image
        id: rechunk-image
        shell: bash
        run: |
          sudo podman run --rm \
            --privileged \
            -v /var/lib/containers:/var/lib/containers \
            "quay.io/centos-bootc/centos-bootc:stream10" \
            /usr/libexec/bootc-base-imagectl rechunk \
              localhost/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
              localhost/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # - name: Use buildah to create the image
      #   id: build-image
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     image: ${{ env.IMAGE_NAME }}
      #     tags: latest ${{ github.sha }}
      #     containerfiles: ./Containerfile
      # Since redhat-actions/buildah-build@v2 doesnt use sudo, run it manually
      # or else rechunker won't work.
      # - name: Build the image
      #   id: build-image
      #   shell: bash
      #   run: |
      #     sudo buildah build --pull=newer --tag raw_img

      # - name: Log in to Github Container registry
      #   uses: redhat-actions/podman-login@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        id: push-to-ghcr
        run: |
          sudo podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          sudo podman tag \
            localhost/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          sudo podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # - name: Push to GHCR
      #   id: push-to-ghcr
      #   uses: redhat-actions/push-to-registry@v2
      #   with:
      #     # image: ${{ steps.build-image.outputs.image }}
      #     # tags: ${{ steps.build-image.outputs.tags }}
      #     image: ${{ env.IMAGE_NAME }}
      #     tags: ${{ env.IMAGE_TAG }}
      #     registry: ${{ env.REGISTRY }}
